openapi: 3.0.0
info:
  title: Thifs is my swagger ui docs
  description: This is my company documentation made by me
  contact:
    email: groverhardik18@gmail.com
  liscence:
    name: Apache 2.0
    url: http:/apache.org/
  version: ""
paths:
  /string:
    get:
      summary: Returns a string
      description: It is just returning a fake string
      responses:
        "200":
          description: succsess
          content:
            "*/*":
              schema:
                type: string
                example: a fake string
        "400":
          description: user error
        "500":
          description: internal server error
  /user:
    get:
      summary: returns a single object
      description: returning a object
      responses:
        "200":
          description: success
          content:
            "*/*":
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
  /users:
    get:
      summary: returns array of users
      description: array return
      responses:
        "200":
          description: success
          content:
            "*/*":
              schema:
                type: array
                items:
                  type: object
                  properites:
                    id:
                      type: integer
                    name:
                      type: string
  /users/{userId}:
    get:
      summary: return array of users
      description: array return
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: success
